name: Build GRID Scanner v3

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Compile
        run: cl /nologo /EHsc /O2 /MT /std:c++17 GRID_Credit_MemoryScanner.cpp /link /OUT:GRID_Credit_MemoryScanner_v3.exe
      - uses: actions/upload-artifact@v4
        with:
          name: GRID-Scanner-v3
          path: GRID_Credit_MemoryScanner_v3.exe
