name: Build GRID Scanner v2

on: [push]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Compile
        run: cl /EHsc /O2 /MT GRID_Credit_MemoryScanner.cpp /link psapi.lib user32.lib /OUT:GRID_Credit_MemoryScanner_v2.exe
      - uses: actions/upload-artifact@v4
        with:
          name: GRID-Scanner-v2
          path: GRID_Credit_MemoryScanner_v2.exe
